#!/usr/bin/env bash
# Prepare the gateway to be reached from anywhere through Tailscale Funnel.
#
#   ./setup_funnel.sh [public-host]        e.g. ./setup_funnel.sh spark-e257.tail803c7f.ts.net
#
# To reuse an existing key (e.g. your DGX API key) instead of generating one:
#   SENSEI_KEY=sk-... ./setup_funnel.sh
#
# Writes (once; delete them to regenerate):
#   turnserver.conf  coturn config: TURN on 127.0.0.1:3478 (TCP), reached only through Funnel,
#                    relaying only to this machine's own LAN address
#   sensei.env       SENSEI_KEY, SENSEI_TURN_SECRET, SENSEI_TURN_URLS for the gateway
# and prints the commands to start everything.
set -euo pipefail
cd "$(dirname "$0")"

HOST="${1:-$(tailscale status --json 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))' 2>/dev/null || true)}"
if [ -z "$HOST" ]; then
  echo "usage: $0 <public-host>   (e.g. spark-e257.tail803c7f.ts.net)" >&2
  exit 1
fi
# The address coturn relays from and to: the gateway's own LAN address.
LAN_IP="${SENSEI_LAN_IP:-$(hostname -I | awk '{print $1}')}"

if [ ! -f sensei.env ]; then
  KEY="${SENSEI_KEY:-$(python3 -c 'import secrets; print(secrets.token_urlsafe(12))')}"
  SECRET=$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')
  cat > sensei.env <<EOF
SENSEI_KEY=$KEY
SENSEI_TURN_SECRET=$SECRET
SENSEI_TURN_URLS=turns:$HOST:10000?transport=tcp
EOF
  chmod 600 sensei.env
fi
SECRET=$(grep '^SENSEI_TURN_SECRET=' sensei.env | cut -d= -f2-)
KEY=$(grep '^SENSEI_KEY=' sensei.env | cut -d= -f2-)

if [ ! -f turnserver.conf ]; then
  cat > turnserver.conf <<EOF
# Generated by setup_funnel.sh. TURN for Sensei Cam, reached only through Tailscale Funnel.
listening-ip=127.0.0.1
listening-port=3478
relay-ip=$LAN_IP
min-port=49160
max-port=49200
realm=sensei
fingerprint
use-auth-secret
static-auth-secret=$SECRET
# Funnel terminates TLS and forwards plain TCP here; no UDP/TLS listeners needed.
no-udp
no-tls
no-dtls
no-cli
# Relay only to this machine (the gateway), never to the rest of the network or internet.
denied-peer-ip=0.0.0.0-255.255.255.255
denied-peer-ip=::-ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
allowed-peer-ip=$LAN_IP
log-file=stdout
simple-log
# Run as a normal user: keep coturn's pid file and (unused) user DB out of root-owned dirs.
pidfile=/var/tmp/turnserver.pid
userdb=/var/tmp/turndb
EOF
  chmod 600 turnserver.conf
fi

cat <<EOF
Wrote sensei.env and turnserver.conf (LAN address $LAN_IP, public host $HOST).

Start these, each in its own tmux window, from $(pwd):
  sudo systemctl disable --now coturn   # once, if apt started the stock service
  turnserver -c turnserver.conf
  set -a; source sensei.env; set +a; uvicorn server:app --host 0.0.0.0 --port 8787

Open them to the internet through Funnel (once; they persist):
  sudo tailscale funnel --bg --https=8443 http://localhost:8787
  sudo tailscale funnel --bg --tls-terminated-tcp=10000 tcp://localhost:3478
  tailscale funnel status

Phone app:   server  https://$HOST:8443
             key     $KEY
Console:     https://$HOST:8443/?key=$KEY
EOF
